name: TS-Project
run-name: AWS create resources
on: [push]
jobs:
  Deploy-App:
    runs-on: ubuntu-latest
    steps:
      - run : echo "Deploying the app"
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: List file in repo
        run: ls ${{ github.workspace }}
      # Install the deps
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
      - name: Check if aws is installed
        run: |
          aws --version
      - name: install terraform
        uses: hashicorp/setup-terraform@v2
      - run: terraform version
      # Configure AWS CLI
      - run: mkdir -p  ~/.aws/
      - run: echo "$super_secret" > ~/.aws/credentials
        env: 
          super_secret: ${{ secrets.AWS_CONFIG }}
      - run: cat ~/.aws/credentials
      - run: aws configure list-profiles
      - run: aws s3 ls --region eu-central-1 --profile JasonT
      # Terraform stuff :)
      - run: echo "${STATE_BUCKET}" && terraform -chdir=terraform/ init -backend-config="bucket=${STATE_BUCKET}"
        env:
          STATE_BUCKET: ${{ secrets.TF_BUCKET }}
      - run: terraform -chdir=terraform/ plan 
